version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3008:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5566:5566"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ts_todo_list
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ts_todo_list
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
